ccflags-y := -I$(src)/include

#obj-m	+= gm12u320.o
obj-m	+= hx8357d.o
obj-m	+= ili9225.o
obj-m	+= ili9341.o
obj-m	+= mi0283qt.o
obj-m	+= repaper.o
obj-m	+= st7586.o
obj-m	+= st7735r.o
obj-m	+= st7789v.o
obj-m	+= st7796.o
obj-m   += ili9488.o
obj-m   += panel-jd9366.o